[package]
name = "raymarch"
version = "0.1.0"
authors = ["Martin Tomasi <martin.tomasi@gmail.com>"]

[[bin]]
name = "main"

[dependencies]
nalgebra = "*"
image = "*"
rand = "*"

[profile.release]
debug = true
